#ifndef _USER_CONFIG_OVERRIDE_H_
#define _USER_CONFIG_OVERRIDE_H_
#ifndef SUPPORT_MQTT_EVENT
#define SUPPORT_MQTT_EVENT
#endif
#ifdef RULE_MAX_MQTT_EVENTSZ
#undef RULE_MAX_MQTT_EVENTSZ
#endif
#define RULE_MAX_MQTT_EVENTSZ 512
#endif
