name: Build_firmware_master

on:
  workflow_dispatch:
  push:
    branches: master
    paths-ignore:
    - '.github/**'
    - '**.md'
    - 'tasmota/berry/**'

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  safeboot-nspanel:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
          enable-cache: false
      - name: Install dependencies
        run: |
          uv pip install --system pioarduino
          cp ./platformio_override_sample.ini ./platformio_override.ini
      - name: Add "release" to footer
        run: |
          sed -i -e "s/TASMOTA_SHA_SHORT/TASMOTA_SHA_SHORT release-/g" ./tasmota/include/tasmota_version.h
      - name: Run PlatformIO safeboot
        env:
          PYTHONIOENCODING: utf-8
          PYTHONUTF8: '1'
        run: platformio run -e tasmota32-safeboot
      - name: Upload safeboot artifact
        uses: actions/upload-artifact@v4
        with:
          name: tasmota32-safeboot
          path: ./build_output

  nspanel-image:
    needs: safeboot-nspanel
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
          enable-cache: false
      - name: Install dependencies
        run: |
          uv pip install --system pioarduino
          cp ./platformio_override_sample.ini ./platformio_override.ini
      - name: Download safeboot firmware
        uses: actions/download-artifact@v4
        with:
          pattern: tasmota32*
          path: ./temp
      - name: Move safeboot files
        run: |
          mkdir -p ./firmware/firmware
          find ./temp -type f -exec cp -t ./firmware/firmware {} +
      - name: Add "release" to footer
        run: |
          sed -i -e "s/TASMOTA_SHA_SHORT/TASMOTA_SHA_SHORT release-/g" ./tasmota/include/tasmota_version.h
      - name: Run PlatformIO nspanel
        env:
          PYTHONIOENCODING: utf-8
          PYTHONUTF8: '1'
        run: platformio run -e tasmota32-nspanel
      - name: Upload nspanel firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: tasmota32-nspanel-custom
          path: ./build_output
